# Generated by Django 4.2.2 on 2023-08-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(max_length=150)),
                ('driver', models.CharField(max_length=150)),
                ('pickup_location', models.CharField(max_length=110)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
            ],
        ),
    ]
